### ISSUE TITLE
Mandatory key(s) missing from params array: source_contact_id

### ISSUE THREAD

**Issue by hcallens** [mecachisenros/cf-civicrm#168]
When as a non logged in user I try to submit my form I get a bunch of errors like this:

Mandatory key(s) missing from params array: source_contact_id

#0 ***/wp-content/plugins/cf-civicrm/processors/activity/class-activity-processor.php(117): civicrm_api3('Activity', 'create', Array)
#1 ***/wp-content/plugins/caldera-forms/classes/core.php(3435): CiviCRM_Caldera_Forms_Activity_Processor->processor(Array, Array, '_cf_process_5ef...')
#2 ***/wp-content/plugins/caldera-forms/classes/core.php(5213): Caldera_Forms::process_submission()
#3 ***/wp-content/plugins/caldera-forms/classes/core.php(3831): Caldera_Forms::process_form_via_post()
#4 ***/wp-includes/class-wp-hook.php(287): Caldera_Forms->cf_init_system('')
#5 ***/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#6 ***/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#7 ***/wp-settings.php(562): do_action('wp_loaded')
#8 ***/wp-config.php(93): require_once('/home/mydir/...')
#9 ***/wp-load.php(37): require_once('/home/mydir/...')
#10 ***/wp-blog-header.php(13): require_once('/home/mydir/...')
#11 ***/index.php(17): require('/home/mydir/...')
#12 {main}

When I fill the form when logged in all goes well.

**Desktop:**
 - OS: MacOs
 - Browser: Brave, Firefox

Here is my form:
[contact-nl-export.json.txt](https://github.com/mecachisenros/cf-civicrm/files/4864958/contact-nl-export.json.txt)

Thanks for any help !

**Comment by hcallens** [comment]
The problem was that I didn't add the magic tags for name and email in the contact fields of Contact 1. Problem solved.
